sudo: required

services:
  - docker

before_install:
  - docker build -t y2tehilab/test-image -f ./client/Dockerfile.dev ./client

script:
  - docker run y2tehilab/test-image yarn test -- --coverage

after_success:
  - docker build -t y2tehilab/multi-client ./client
  - docker build -t y2tehilab/multi-server ./server
  - docker build -t y2tehilab/multi-worker ./worker
  - docker build -t y2tehilab/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push y2tehilab/multi-client
  - docker push y2tehilab/multi-server
  - docker push y2tehilab/multi-worker
  - docker push y2tehilab/multi-nginx