version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - complex_db:/var/lib/mysql
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_DATABASE: testing
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: db
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

volumes:
  complex_db: